# Generated by Django 4.2.1 on 2023-05-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_alter_cartproduct_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('place', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
            ],
            options={
                'verbose_name': 'Количество товаров',
                'verbose_name_plural': 'Количество товаров',
                'ordering': ['product_id', 'count'],
            },
        ),
    ]
